"""Convenience layer over the generated client: one object, one call per endpoint.

Generated by scripts/generate-facade.ts from the OpenAPI document; do not edit.
Groups and method names follow the CLI's noun:verb rule.
"""

from __future__ import annotations

import datetime as _dt
from typing import Any

import httpx

from . import api as _ops  # noqa: F401
from . import models as _m
from .client import AuthenticatedClient
from .types import UNSET, Response

DEFAULT_BASE_URL = "https://api.mentio.dev"


class MentioError(Exception):
    """A non-2xx answer: the HTTP `status`, the API's stable `code`, and its `message`."""

    def __init__(self, status: int, code: str, message: str) -> None:
        super().__init__(f"{code}: {message} (HTTP {status})")
        self.status = status
        self.code = code
        self.message = message


def _result(response: Response[Any]) -> Any:
    status = int(response.status_code)
    if 200 <= status < 300:
        return response.parsed
    parsed = response.parsed
    if isinstance(parsed, _m.ErrorResponse):
        raise MentioError(status, parsed.error.code, parsed.error.message)
    raise MentioError(status, f"http_{status}", response.content[:300].decode(errors="replace"))


def _enum(cls: type, value: Any) -> Any:
    if value is UNSET or value is None or isinstance(value, cls):
        return value
    return cls(value)


def _enum_list(cls: type, values: Any) -> Any:
    if values is UNSET or values is None:
        return values
    return [_enum(cls, v) for v in values]


def _instant(_cls: Any, value: Any) -> Any:
    if value is UNSET or value is None or isinstance(value, _dt.datetime):
        return value
    if isinstance(value, (int, float)):
        return _dt.datetime.fromtimestamp(value / 1000, tz=_dt.timezone.utc)
    if isinstance(value, _dt.date):
        return _dt.datetime(value.year, value.month, value.day, tzinfo=_dt.timezone.utc)
    text = str(value).strip()
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    parsed = _dt.datetime.fromisoformat(text)
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=_dt.timezone.utc)


def _coerce(params: dict[str, Any], table: dict[str, tuple[Any, Any]]) -> None:
    for name, (fn, cls) in table.items():
        if name in params:
            params[name] = fn(cls, params[name])


def _body(target: Any, body: Any, fields: dict[str, Any]) -> Any:
    data = body if body is not None else fields
    if not isinstance(data, dict):
        return data
    if isinstance(target, dict):
        kind = data.get("kind")
        cls = target.get(kind)
        if cls is None:
            raise ValueError(f"kind must be one of: {', '.join(target)}")
        return cls.from_dict(data)
    return target.from_dict(data)



import mentio.api.alerts.create_alert  # noqa: F401
import mentio.api.alerts.create_channel  # noqa: F401
import mentio.api.alerts.delete_alert  # noqa: F401
import mentio.api.alerts.delete_channel  # noqa: F401
import mentio.api.alerts.get_alert  # noqa: F401
import mentio.api.alerts.get_channel  # noqa: F401
import mentio.api.alerts.list_alerts  # noqa: F401
import mentio.api.alerts.list_channel_deliveries  # noqa: F401
import mentio.api.alerts.list_channels  # noqa: F401
import mentio.api.alerts.mute_alert_authors  # noqa: F401
import mentio.api.alerts.rotate_webhook_secret  # noqa: F401
import mentio.api.alerts.run_alert_digest  # noqa: F401
import mentio.api.alerts.test_alert  # noqa: F401
import mentio.api.alerts.test_channel  # noqa: F401
import mentio.api.alerts.unmute_alert_authors  # noqa: F401
import mentio.api.alerts.update_alert  # noqa: F401
import mentio.api.alerts.update_channel  # noqa: F401
import mentio.api.analytics.get_analytics_breakdown  # noqa: F401
import mentio.api.analytics.get_analytics_series  # noqa: F401
import mentio.api.analytics.get_analytics_summary  # noqa: F401
import mentio.api.analytics.get_share_of_voice  # noqa: F401
import mentio.api.api_keys.create_api_key  # noqa: F401
import mentio.api.api_keys.list_api_keys  # noqa: F401
import mentio.api.api_keys.revoke_api_key  # noqa: F401
import mentio.api.company.get_company  # noqa: F401
import mentio.api.company.update_company  # noqa: F401
import mentio.api.keywords.create_keyword  # noqa: F401
import mentio.api.keywords.delete_keyword  # noqa: F401
import mentio.api.keywords.get_keyword  # noqa: F401
import mentio.api.keywords.list_keywords  # noqa: F401
import mentio.api.keywords.update_keyword  # noqa: F401
import mentio.api.mentions.export_mentions_csv  # noqa: F401
import mentio.api.mentions.get_mention  # noqa: F401
import mentio.api.mentions.search_mentions  # noqa: F401
import mentio.api.mentions.update_mention  # noqa: F401
import mentio.api.people.export_people_csv  # noqa: F401
import mentio.api.people.get_person  # noqa: F401
import mentio.api.people.list_people  # noqa: F401
import mentio.api.people.merge_people  # noqa: F401
import mentio.api.people.split_person  # noqa: F401
import mentio.api.people.update_person  # noqa: F401
import mentio.api.segments.create_segment  # noqa: F401
import mentio.api.segments.delete_segment  # noqa: F401
import mentio.api.segments.get_segment  # noqa: F401
import mentio.api.segments.list_segments  # noqa: F401
import mentio.api.segments.update_segment  # noqa: F401
import mentio.api.system.get_health  # noqa: F401


class _Keywords:
    """keywords: create, delete, get, list, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    def create(self, body: dict[str, Any] | _m.CreateKeywordBody | None = None, **fields: Any) -> _m.Keyword:
        """Track a keyword

        Start tracking a word or phrase. Matching, classification and delivery begin on the next poll. A funded workspace tracks up to 500 keywords; each costs $5 per month, deducted daily from the balance.

        Body: a dict, a model, or the fields as keyword arguments:
          term (required): The word or phrase to track, matched case-insensitively as a phrase.
          kind: brand: your own names. competitor: theirs. topic: the space. Drives share of voice and segments.
          platforms: Platforms to track it on; omit or null for every platform."""
        return _result(_ops.keywords.create_keyword.sync_detailed(client=self._client, body=_body(_m.CreateKeywordBody, body, fields)))

    def delete(self, id: str) -> Any:
        """Delete a keyword

        Removes the keyword and its matches. Posts also matched by another keyword stay."""
        return _result(_ops.keywords.delete_keyword.sync_detailed(id, client=self._client))

    def get(self, id: str) -> _m.Keyword:
        """Get a keyword"""
        return _result(_ops.keywords.get_keyword.sync_detailed(id, client=self._client))

    def list(self) -> _m.ListKeywordsResponse200:
        """List keywords

        Every keyword of the workspace, newest first, with its match stats and poll health."""
        return _result(_ops.keywords.list_keywords.sync_detailed(client=self._client))

    def update(self, id: str, body: dict[str, Any] | _m.UpdateKeywordBody | None = None, **fields: Any) -> _m.Keyword:
        """Update a keyword

        Mute or unmute it, or change the platforms it is tracked on.

        Body: a dict, a model, or the fields as keyword arguments:
          muted: A muted keyword stops polling and matching; its mentions stay.
          platforms: Replaces the platform list; null means every platform."""
        return _result(_ops.keywords.update_keyword.sync_detailed(id, client=self._client, body=_body(_m.UpdateKeywordBody, body, fields)))

class _Mentions:
    """mentions: export, get, search, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    def export(self, **params: Any) -> str:
        """Export mentions as CSV

        The same mentions GET /v1/mentions would list for these filters, as CSV, newest matched first (the order they entered your feed, which can differ from the post date): id, published_at, platform, keyword, author, author_url, author_followers, relevance, sentiment, intents (pipe-separated), status, relevant, delivered, url, text (first 1,000 characters). Capped at 10,000 rows; the X-Mentions-Truncated header says when the cap cut the list. At most 6 exports per minute per workspace; a 429 carries Retry-After.

        Keyword arguments (query):
          keyword_id: Only matches of this keyword.
          platform: Only posts from this platform.
          status: Only mentions in this status. Omit for every status.
          relevant: true: only mentions the classifier scored relevant; false: only the rest (unclassified included).
          sentiment: Only this sentiment.
          intent: Only mentions carrying this intent (buy_intent, question, complaint, praise, comparison).
          person_id: Only this person (an id from /v1/people), merged accounts included. Implies includeMuted.
          include_muted: true: include mentions by people you muted, hidden by default.
          assignee_id: Only mentions assigned to this workspace member (user id).
          snoozed: true: only mentions currently snoozed. Otherwise snoozed mentions stay out until they wake.
          exclude_authors: Hide these authors: display names, handles or profile URLs. Repeatable, or one comma-separated value.
          min_relevance: Only mentions scored at least this; unclassified ones are excluded.
          min_followers: Only authors with at least this many followers. Unknown reach never passes.
          tags: Only authors your workspace tagged with any of these (exact, case-sensitive). Repeatable, or comma-separated.
          link_hosts: Only posts linking to any of these hosts, the host itself or a subdomain of it (octolens.com also matches blog.octolens.com). Repeatable, or comma-separated.
          q: Substring search in the post text.
          since: Only posts published at or after this instant (ISO 8601, or epoch ms).
          until: Only posts published at or before this instant (ISO 8601, or epoch ms)."""
        _coerce(params, {"platform": (_enum, _m.ExportMentionsCsvPlatform), "status": (_enum, _m.ExportMentionsCsvStatus), "sentiment": (_enum, _m.ExportMentionsCsvSentiment), "since": (_instant, None), "until": (_instant, None)})
        return _result(_ops.mentions.export_mentions_csv.sync_detailed(client=self._client, **params))

    def get(self, id: str) -> _m.Mention:
        """Get a mention

        One mention by id, as it appears in the list: the post, its author with reach and your tags, the classification, the priority score and the triage fields. Ids belong to your organization; any other id is a 404."""
        return _result(_ops.mentions.get_mention.sync_detailed(id, client=self._client))

    def search(self, **params: Any) -> _m.SearchMentionsResponse200:
        """List mentions

        Mentions matched to your keywords, filtered and paginated. Default order is newest match first; sort=priority ranks the last 30 days of matches by attention score. Page with nextCursor, passing the same filters and sort. A mention is one post matched to one keyword.

        Keyword arguments (query):
          keyword_id: Only matches of this keyword.
          platform: Only posts from this platform.
          status: Only mentions in this status. Omit for every status.
          relevant: true: only mentions the classifier scored relevant; false: only the rest (unclassified included).
          sentiment: Only this sentiment.
          intent: Only mentions carrying this intent (buy_intent, question, complaint, praise, comparison).
          person_id: Only this person (an id from /v1/people), merged accounts included. Implies includeMuted.
          include_muted: true: include mentions by people you muted, hidden by default.
          assignee_id: Only mentions assigned to this workspace member (user id).
          snoozed: true: only mentions currently snoozed. Otherwise snoozed mentions stay out until they wake.
          exclude_authors: Hide these authors: display names, handles or profile URLs. Repeatable, or one comma-separated value.
          min_relevance: Only mentions scored at least this; unclassified ones are excluded.
          min_followers: Only authors with at least this many followers. Unknown reach never passes.
          tags: Only authors your workspace tagged with any of these (exact, case-sensitive). Repeatable, or comma-separated.
          link_hosts: Only posts linking to any of these hosts, the host itself or a subdomain of it (octolens.com also matches blog.octolens.com). Repeatable, or comma-separated.
          q: Substring search in the post text.
          since: Only posts published at or after this instant (ISO 8601, or epoch ms).
          until: Only posts published at or before this instant (ISO 8601, or epoch ms).
          sort: newest: by match time, newest first. priority: by attention score, highest first; priority ranks the last 30 days of matches only, older ones stay reachable under newest. Cursors are specific to a sort.
          cursor: nextCursor from the previous page; pass the same filters and sort.
          limit: Page size, 1 to 100."""
        _coerce(params, {"platform": (_enum, _m.SearchMentionsPlatform), "status": (_enum, _m.SearchMentionsStatus), "sentiment": (_enum, _m.SearchMentionsSentiment), "since": (_instant, None), "until": (_instant, None), "sort": (_enum, _m.SearchMentionsSort)})
        return _result(_ops.mentions.search_mentions.sync_detailed(client=self._client, **params))

    def update(self, id: str, body: dict[str, Any] | _m.UpdateMentionBody | None = None, **fields: Any) -> _m.Mention:
        """Update a mention

        The one write on a mention. Set status to ignored or done to handle it (open puts it back), assign it to a workspace member, snooze it out of the feed, or leave an internal note. Null clears a field; omitted fields are untouched. Delivery and billing never change.

        Body: a dict, a model, or the fields as keyword arguments:
          status: ignored or done to handle it; open to put it back.
          assigneeId: A workspace member (user id), or null to unassign.
          snoozedUntil: ISO 8601 (or epoch ms) until which the mention leaves the feed; null wakes it.
          note: Internal note; null or empty clears it."""
        return _result(_ops.mentions.update_mention.sync_detailed(id, client=self._client, body=_body(_m.UpdateMentionBody, body, fields)))

class _People:
    """people: export, get, list, merge, split, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    def export(self, **params: Any) -> str:
        """Export people as CSV

        The same list as GET /v1/people (segmentId included) as CSV, one row per person with their contact columns: handle, followers, email, website, company, location, tags. Capped at 5,000 people. At most 6 exports per minute per workspace; a 429 carries Retry-After.

        Keyword arguments (query):
          platform: People with an account on this platform.
          q: Matches the display name or the profile handle or URL, case-insensitively.
          tag: Only people carrying this tag (exact, case-sensitive).
          muted: true: only muted people; false: only unmuted; omitted: everyone.
          since: Only people whose first matched mention is at or after this instant (ISO 8601, or epoch ms).
          segment_id: A saved segment applied on top of every other filter here. Unknown id: 404.
          platforms: People with an account on any of these platforms. Repeatable, or comma-separated.
          tags: People carrying any of these tags. Repeatable, or comma-separated.
          min_followers: At least this many followers. Unknown reach never matches.
          max_followers: At most this many followers.
          min_mentions: At least this many matched mentions.
          min_negative: At least this many negative mentions.
          intents: At least one mention carrying any of these intents.
          keyword_kinds: Mentioned a keyword of any of these kinds.
          never_keyword_kinds: Never mentioned a keyword of these kinds.
          new_since_days: First seen within this many days.
          link_hosts: People with at least one mention linking to any of these hosts, the host itself or a subdomain of it. Repeatable, or comma-separated.
          sort: mentions: most matches first. recent: last seen first. reach: most followers first, unknown last. new: first seen most recently first."""
        _coerce(params, {"platform": (_enum, _m.ExportPeopleCsvPlatform), "since": (_instant, None), "platforms": (_enum_list, _m.ExportPeopleCsvPlatformsItem), "keyword_kinds": (_enum_list, _m.ExportPeopleCsvKeywordKindsItem), "sort": (_enum, _m.ExportPeopleCsvSort)})
        return _result(_ops.people.export_people_csv.sync_detailed(client=self._client, **params))

    def get(self, id: str) -> _m.Person:
        """Get a person

        One person as your workspace sees them. An account merged into someone resolves to that person."""
        return _result(_ops.people.get_person.sync_detailed(id, client=self._client))

    def list(self, **params: Any) -> _m.ListPeopleResponse200:
        """List people

        The people behind your mentions: one row per person, with their accounts, reach, public profile, per-workspace stats and your annotations. Filter by platform, tag, follower range, mention counts, intents seen, keyword kinds mentioned or never mentioned, or a saved segment. Offset-paginated with a total.

        Keyword arguments (query):
          platform: People with an account on this platform.
          q: Matches the display name or the profile handle or URL, case-insensitively.
          tag: Only people carrying this tag (exact, case-sensitive).
          muted: true: only muted people; false: only unmuted; omitted: everyone.
          since: Only people whose first matched mention is at or after this instant (ISO 8601, or epoch ms).
          segment_id: A saved segment applied on top of every other filter here. Unknown id: 404.
          platforms: People with an account on any of these platforms. Repeatable, or comma-separated.
          tags: People carrying any of these tags. Repeatable, or comma-separated.
          min_followers: At least this many followers. Unknown reach never matches.
          max_followers: At most this many followers.
          min_mentions: At least this many matched mentions.
          min_negative: At least this many negative mentions.
          intents: At least one mention carrying any of these intents.
          keyword_kinds: Mentioned a keyword of any of these kinds.
          never_keyword_kinds: Never mentioned a keyword of these kinds.
          new_since_days: First seen within this many days.
          link_hosts: People with at least one mention linking to any of these hosts, the host itself or a subdomain of it. Repeatable, or comma-separated.
          sort: mentions: most matches first. recent: last seen first. reach: most followers first, unknown last. new: first seen most recently first.
          limit: Page size, 1 to 100.
          offset: Skip this many people. Offset paging: a grouped read over hundreds of people, not a stream."""
        _coerce(params, {"platform": (_enum, _m.ListPeoplePlatform), "since": (_instant, None), "platforms": (_enum_list, _m.ListPeoplePlatformsItem), "keyword_kinds": (_enum_list, _m.ListPeopleKeywordKindsItem), "never_keyword_kinds": (_enum_list, _m.ListPeopleNeverKeywordKindsItem), "sort": (_enum, _m.ListPeopleSort)})
        return _result(_ops.people.list_people.sync_detailed(client=self._client, **params))

    def merge(self, id: str, body: dict[str, Any] | _m.MergePeopleBody | None = None, **fields: Any) -> _m.Person:
        """Merge an account into a person

        Declare that this account and another person are the same human, for your workspace only. Their mentions, tags and notes combine under the person named by `into`.

        Body: a dict, a model, or the fields as keyword arguments:
          into (required): The person to fold this account into (their id)."""
        return _result(_ops.people.merge_people.sync_detailed(id, client=self._client, body=_body(_m.MergePeopleBody, body, fields)))

    def split(self, id: str) -> _m.Person:
        """Undo a merge

        The account becomes its own person again."""
        return _result(_ops.people.split_person.sync_detailed(id, client=self._client))

    def update(self, id: str, body: dict[str, Any] | _m.UpdatePersonBody | None = None, **fields: Any) -> _m.Person:
        """Update your annotations on a person

        Tags, notes and mute, for your workspace only. Mute hides their posts from your feed and every channel; ingest and billing never change.

        Body: a dict, a model, or the fields as keyword arguments:
          tags: Replaces the whole list.
          notes:
          muted:"""
        return _result(_ops.people.update_person.sync_detailed(id, client=self._client, body=_body(_m.UpdatePersonBody, body, fields)))

class _Segments:
    """segments: create, delete, get, list, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    def create(self, body: dict[str, Any] | _m.CreateSegmentBody | None = None, **fields: Any) -> _m.Segment:
        """Create a segment

        Body: a dict, a model, or the fields as keyword arguments:
          name (required):
          description:
          filter:"""
        return _result(_ops.segments.create_segment.sync_detailed(client=self._client, body=_body(_m.CreateSegmentBody, body, fields)))

    def delete(self, id: str) -> Any:
        """Delete a segment

        Nobody in it is affected."""
        return _result(_ops.segments.delete_segment.sync_detailed(id, client=self._client))

    def get(self, id: str) -> _m.Segment:
        """Get a segment"""
        return _result(_ops.segments.get_segment.sync_detailed(id, client=self._client))

    def list(self) -> _m.ListSegmentsResponse200:
        """List segments

        Your saved segments, each with the number of people in it right now (segments are evaluated on every read, never materialized), plus presets you can save as a starting point. Pass a segment id to GET /v1/people to list its members."""
        return _result(_ops.segments.list_segments.sync_detailed(client=self._client))

    def update(self, id: str, body: dict[str, Any] | _m.UpdateSegmentBody | None = None, **fields: Any) -> _m.Segment:
        """Update a segment

        Body: a dict, a model, or the fields as keyword arguments:
          name:
          description:
          filter: Replaces the whole filter."""
        return _result(_ops.segments.update_segment.sync_detailed(id, client=self._client, body=_body(_m.UpdateSegmentBody, body, fields)))

class _Alerts:
    """alerts: create, delete, get, list, mute, run, test, unmute, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    def create(self, body: dict[str, Any] | _m.CreateAlertBody | None = None, **fields: Any) -> _m.Alert:
        """Create an alert

        Body: a dict, a model, or the fields as keyword arguments:
          name (required):
          enabled:
          mode:
          filter:
          schedule: Required for daily alerts.
          event: Custom event name for webhook payloads; null for the mode default.
          channelIds: Channel ids from GET /v1/channels."""
        return _result(_ops.alerts.create_alert.sync_detailed(client=self._client, body=_body(_m.CreateAlertBody, body, fields)))

    def delete(self, id: str) -> Any:
        """Delete an alert"""
        return _result(_ops.alerts.delete_alert.sync_detailed(id, client=self._client))

    def get(self, id: str) -> _m.Alert:
        """Get an alert"""
        return _result(_ops.alerts.get_alert.sync_detailed(id, client=self._client))

    def list(self) -> _m.ListAlertsResponse200:
        """List alerts"""
        return _result(_ops.alerts.list_alerts.sync_detailed(client=self._client))

    def mute(self, id: str, body: dict[str, Any] | _m.MuteAlertAuthorsBody | None = None, **fields: Any) -> _m.Alert:
        """Mute authors on an alert

        Add authors to the alert's muted list without touching the rest of its filter. Links are read the way the dashboard reads them: a post link mutes its author, twitter.com becomes x.com, a Hacker News profile keeps its id. Authors already muted are skipped, so a retry is safe. An entry that names no person (a subreddit, a story) rejects the request with that entry named.

        Body: a dict, a model, or the fields as keyword arguments:
          authors (required): Profile or post links (x.com/name, linkedin.com/in/name, reddit.com/user/name, a post URL), handles (@name, u/name), Bluesky DIDs or display names. A link is stored as the author's profile; a plain name or handle matches that name on every platform."""
        return _result(_ops.alerts.mute_alert_authors.sync_detailed(id, client=self._client, body=_body(_m.MuteAlertAuthorsBody, body, fields)))

    def run(self, id: str) -> _m.RunAlertDigestResponse200:
        """Send a digest now"""
        return _result(_ops.alerts.run_alert_digest.sync_detailed(id, client=self._client))

    def test(self, id: str) -> _m.TestAlertResponse200:
        """Send a test through an alert's channels"""
        return _result(_ops.alerts.test_alert.sync_detailed(id, client=self._client))

    def unmute(self, id: str, body: dict[str, Any] | _m.UnmuteAlertAuthorsBody | None = None, **fields: Any) -> _m.Alert:
        """Unmute authors on an alert

        Remove authors from the alert's muted list without touching the rest of its filter. Name each one by the stored entry or by any link to that profile or its posts. Authors that are not muted are ignored, so a retry is safe.

        Body: a dict, a model, or the fields as keyword arguments:
          authors (required): Profile or post links (x.com/name, linkedin.com/in/name, reddit.com/user/name, a post URL), handles (@name, u/name), Bluesky DIDs or display names. A link is stored as the author's profile; a plain name or handle matches that name on every platform."""
        return _result(_ops.alerts.unmute_alert_authors.sync_detailed(id, client=self._client, body=_body(_m.UnmuteAlertAuthorsBody, body, fields)))

    def update(self, id: str, body: dict[str, Any] | _m.UpdateAlertBody | None = None, **fields: Any) -> _m.Alert:
        """Update an alert

        Body: a dict, a model, or the fields as keyword arguments:
          name:
          enabled:
          mode:
          filter: Replaces the whole filter.
          schedule:
          event:
          channelIds: Replaces the whole list."""
        return _result(_ops.alerts.update_alert.sync_detailed(id, client=self._client, body=_body(_m.UpdateAlertBody, body, fields)))

class _Channels:
    """channels: create, delete, deliveries, get, list, rotate_secret, test, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    def create(self, body: dict[str, Any] | _m.CreateSlackChannel | _m.CreateEmailChannel | _m.CreateWebhookChannel | None = None, **fields: Any) -> Any:
        """Create a channel

        Body: a dict with `kind` (slack, email, webhook) or a model; fields may also be passed as keyword arguments:
          kind:
          channelId: A Slack channel id from the connected workspace.
          channelName: The channel name, for the label.
          emails: Each address gets a confirmation link; workspace members are confirmed on sight.
          url: Where the signed POSTs go. https in production.
          label: A name for the channel; the host of the URL when omitted.
          headers: Extra request headers to send, for your own auth."""
        return _result(_ops.alerts.create_channel.sync_detailed(client=self._client, body=_body({"slack": _m.CreateSlackChannel, "email": _m.CreateEmailChannel, "webhook": _m.CreateWebhookChannel}, body, fields)))

    def delete(self, id: str) -> Any:
        """Delete a channel"""
        return _result(_ops.alerts.delete_channel.sync_detailed(id, client=self._client))

    def deliveries(self, id: str, **params: Any) -> _m.ListChannelDeliveriesResponse200:
        """List deliveries to a channel

        Keyword arguments (query):
          limit:"""
        return _result(_ops.alerts.list_channel_deliveries.sync_detailed(id, client=self._client, **params))

    def get(self, id: str) -> Any:
        """Get a channel"""
        return _result(_ops.alerts.get_channel.sync_detailed(id, client=self._client))

    def list(self) -> _m.ListChannelsResponse200:
        """List channels"""
        return _result(_ops.alerts.list_channels.sync_detailed(client=self._client))

    def rotate_secret(self, id: str) -> Any:
        """Rotate a webhook secret"""
        return _result(_ops.alerts.rotate_webhook_secret.sync_detailed(id, client=self._client))

    def test(self, id: str) -> _m.TestChannelResponse200:
        """Send a test to a channel"""
        return _result(_ops.alerts.test_channel.sync_detailed(id, client=self._client))

    def update(self, id: str, body: dict[str, Any] | _m.UpdateChannelBody | None = None, **fields: Any) -> Any:
        """Update a channel

        Body: a dict, a model, or the fields as keyword arguments:
          label:
          url: Webhooks only.
          headers: Webhooks only; replaces the whole set."""
        return _result(_ops.alerts.update_channel.sync_detailed(id, client=self._client, body=_body(_m.UpdateChannelBody, body, fields)))

class _Company:
    """company: get, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    def get(self) -> _m.Company:
        """Get the company profile

        What the classifier knows about you: name, description, use cases, your own accounts, and the composed context it reads."""
        return _result(_ops.company.get_company.sync_detailed(client=self._client))

    def update(self, body: dict[str, Any] | _m.UpdateCompanyBody | None = None, **fields: Any) -> _m.Company:
        """Update the company profile

        Changing profile fields recomposes the classifier context; setting `context` directly overrides it until the next profile edit. Relevance scores for new mentions follow at once.

        Body: a dict, a model, or the fields as keyword arguments:
          name:
          description:
          useCases: Replaces the whole list.
          accounts:
          context: Overrides the composed context until the next profile edit."""
        return _result(_ops.company.update_company.sync_detailed(client=self._client, body=_body(_m.UpdateCompanyBody, body, fields)))

class _Analytics:
    """analytics: breakdown, series, share_of_voice, summary."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    def breakdown(self, **params: Any) -> _m.AnalyticsBreakdown:
        """Mentions grouped by one dimension

        One table of matched, relevant and sentiment counts grouped by `by`: platform, keyword, sentiment, intent, status, hour (weekday and hour of day) or person. The window is `range` (7d, 30d, 90d, 365d, ending today) or `from` and `to`, cut into days in `timezone` (UTC by default); `keywordIds` and `platforms` narrow it; `compare=true` adds the period of the same length right before it. Time axis is the publish date.

        Keyword arguments (query):
          range_: Preset window ending today. Ignored when from or to is given. Default 30d.
          from_: First day, YYYY-MM-DD, inclusive, in `timezone`.
          to: Last day, YYYY-MM-DD, inclusive, in `timezone`. Default today.
          keyword_ids: Only these keyword ids. Repeatable, or comma-separated; omit for every keyword.
          platforms: Only these platforms. Repeatable, or comma-separated; omit for every platform.
          compare: true adds the period of the same length right before the window as `previous`.
          timezone: IANA zone the days are cut in (Europe/Madrid). Default UTC. One offset, the zone's at the end of the window, applies to the whole window.
          by: The dimension to group by: platform, keyword, sentiment (unclassified included), intent (a mention can carry several), status (open, ignored, done), hour (weekday and hour of day in `timezone`), person (who posted; anonymous posts are left out)."""
        _coerce(params, {"range_": (_enum, _m.GetAnalyticsBreakdownRange), "platforms": (_enum_list, _m.GetAnalyticsBreakdownPlatformsItem), "by": (_enum, _m.GetAnalyticsBreakdownBy)})
        return _result(_ops.analytics.get_analytics_breakdown.sync_detailed(client=self._client, **params))

    def series(self, **params: Any) -> _m.AnalyticsSeries:
        """Mentions over time

        Matched, relevant and sentiment counts per day or week across the window, as one total series or split per platform or per keyword with `by`. The window is `range` (7d, 30d, 90d, 365d, ending today) or `from` and `to`, cut into days in `timezone` (UTC by default); `keywordIds` and `platforms` narrow it; `compare=true` adds the period of the same length right before it. Time axis is the publish date.

        Keyword arguments (query):
          range_: Preset window ending today. Ignored when from or to is given. Default 30d.
          from_: First day, YYYY-MM-DD, inclusive, in `timezone`.
          to: Last day, YYYY-MM-DD, inclusive, in `timezone`. Default today.
          keyword_ids: Only these keyword ids. Repeatable, or comma-separated; omit for every keyword.
          platforms: Only these platforms. Repeatable, or comma-separated; omit for every platform.
          compare: true adds the period of the same length right before the window as `previous`.
          timezone: IANA zone the days are cut in (Europe/Madrid). Default UTC. One offset, the zone's at the end of the window, applies to the whole window.
          bucket: Point granularity. Default: day up to 90 days, week beyond. Weeks start on Monday.
          by: Split into one series per platform or per keyword (the top 20 by matched, the rest folded into "other"). Omit for one total series."""
        _coerce(params, {"range_": (_enum, _m.GetAnalyticsSeriesRange), "platforms": (_enum_list, _m.GetAnalyticsSeriesPlatformsItem), "bucket": (_enum, _m.GetAnalyticsSeriesBucket), "by": (_enum, _m.GetAnalyticsSeriesBy)})
        return _result(_ops.analytics.get_analytics_series.sync_detailed(client=self._client, **params))

    def share_of_voice(self, **params: Any) -> _m.ShareOfVoice:
        """Brand against competitors

        Every keyword matched in the window with its counts and its share of brand plus competitor matches; topic keywords are counted but stay out of the split. The window is `range` (7d, 30d, 90d, 365d, ending today) or `from` and `to`, cut into days in `timezone` (UTC by default); `keywordIds` and `platforms` narrow it; `compare=true` adds the period of the same length right before it. Time axis is the publish date.

        Keyword arguments (query):
          range_: Preset window ending today. Ignored when from or to is given. Default 30d.
          from_: First day, YYYY-MM-DD, inclusive, in `timezone`.
          to: Last day, YYYY-MM-DD, inclusive, in `timezone`. Default today.
          keyword_ids: Only these keyword ids. Repeatable, or comma-separated; omit for every keyword.
          platforms: Only these platforms. Repeatable, or comma-separated; omit for every platform.
          compare: true adds the period of the same length right before the window as `previous`.
          timezone: IANA zone the days are cut in (Europe/Madrid). Default UTC. One offset, the zone's at the end of the window, applies to the whole window."""
        _coerce(params, {"range_": (_enum, _m.GetShareOfVoiceRange), "platforms": (_enum_list, _m.GetShareOfVoicePlatformsItem)})
        return _result(_ops.analytics.get_share_of_voice.sync_detailed(client=self._client, **params))

    def summary(self, **params: Any) -> _m.AnalyticsSummary:
        """Headline counts for a window

        Matched and relevant mentions, distinct posts and people, sentiment, buying intent and questions, estimated reach, and where the matches stand in triage. The window is `range` (7d, 30d, 90d, 365d, ending today) or `from` and `to`, cut into days in `timezone` (UTC by default); `keywordIds` and `platforms` narrow it; `compare=true` adds the period of the same length right before it. Time axis is the publish date.

        Keyword arguments (query):
          range_: Preset window ending today. Ignored when from or to is given. Default 30d.
          from_: First day, YYYY-MM-DD, inclusive, in `timezone`.
          to: Last day, YYYY-MM-DD, inclusive, in `timezone`. Default today.
          keyword_ids: Only these keyword ids. Repeatable, or comma-separated; omit for every keyword.
          platforms: Only these platforms. Repeatable, or comma-separated; omit for every platform.
          compare: true adds the period of the same length right before the window as `previous`.
          timezone: IANA zone the days are cut in (Europe/Madrid). Default UTC. One offset, the zone's at the end of the window, applies to the whole window."""
        _coerce(params, {"range_": (_enum, _m.GetAnalyticsSummaryRange), "platforms": (_enum_list, _m.GetAnalyticsSummaryPlatformsItem)})
        return _result(_ops.analytics.get_analytics_summary.sync_detailed(client=self._client, **params))

class _ApiKeys:
    """api-keys: create, list, revoke."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    def create(self, body: dict[str, Any] | _m.CreateApiKeyBody | None = None, **fields: Any) -> _m.CreateApiKeyResponse201:
        """Create an API key

        Mint a key for this workspace. The key itself is returned once; only its hash is stored.

        Body: a dict, a model, or the fields as keyword arguments:
          name: A label for the key; "default" when omitted.
          scope: read: GET only. write: everything."""
        return _result(_ops.api_keys.create_api_key.sync_detailed(client=self._client, body=_body(_m.CreateApiKeyBody, body, fields)))

    def list(self) -> _m.ListApiKeysResponse200:
        """List API keys"""
        return _result(_ops.api_keys.list_api_keys.sync_detailed(client=self._client))

    def revoke(self, id: str) -> Any:
        """Revoke an API key

        Takes effect at once on the API and within a few minutes on cached verifications."""
        return _result(_ops.api_keys.revoke_api_key.sync_detailed(id, client=self._client))

class _System:
    """system: health."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    def health(self) -> _m.GetHealthResponse200:
        """getHealth"""
        return _result(_ops.system.get_health.sync_detailed(client=self._client))

class _AsyncKeywords:
    """keywords: create, delete, get, list, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    async def create(self, body: dict[str, Any] | _m.CreateKeywordBody | None = None, **fields: Any) -> _m.Keyword:
        """Track a keyword

        Start tracking a word or phrase. Matching, classification and delivery begin on the next poll. A funded workspace tracks up to 500 keywords; each costs $5 per month, deducted daily from the balance.

        Body: a dict, a model, or the fields as keyword arguments:
          term (required): The word or phrase to track, matched case-insensitively as a phrase.
          kind: brand: your own names. competitor: theirs. topic: the space. Drives share of voice and segments.
          platforms: Platforms to track it on; omit or null for every platform."""
        return _result(await _ops.keywords.create_keyword.asyncio_detailed(client=self._client, body=_body(_m.CreateKeywordBody, body, fields)))

    async def delete(self, id: str) -> Any:
        """Delete a keyword

        Removes the keyword and its matches. Posts also matched by another keyword stay."""
        return _result(await _ops.keywords.delete_keyword.asyncio_detailed(id, client=self._client))

    async def get(self, id: str) -> _m.Keyword:
        """Get a keyword"""
        return _result(await _ops.keywords.get_keyword.asyncio_detailed(id, client=self._client))

    async def list(self) -> _m.ListKeywordsResponse200:
        """List keywords

        Every keyword of the workspace, newest first, with its match stats and poll health."""
        return _result(await _ops.keywords.list_keywords.asyncio_detailed(client=self._client))

    async def update(self, id: str, body: dict[str, Any] | _m.UpdateKeywordBody | None = None, **fields: Any) -> _m.Keyword:
        """Update a keyword

        Mute or unmute it, or change the platforms it is tracked on.

        Body: a dict, a model, or the fields as keyword arguments:
          muted: A muted keyword stops polling and matching; its mentions stay.
          platforms: Replaces the platform list; null means every platform."""
        return _result(await _ops.keywords.update_keyword.asyncio_detailed(id, client=self._client, body=_body(_m.UpdateKeywordBody, body, fields)))

class _AsyncMentions:
    """mentions: export, get, search, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    async def export(self, **params: Any) -> str:
        """Export mentions as CSV

        The same mentions GET /v1/mentions would list for these filters, as CSV, newest matched first (the order they entered your feed, which can differ from the post date): id, published_at, platform, keyword, author, author_url, author_followers, relevance, sentiment, intents (pipe-separated), status, relevant, delivered, url, text (first 1,000 characters). Capped at 10,000 rows; the X-Mentions-Truncated header says when the cap cut the list. At most 6 exports per minute per workspace; a 429 carries Retry-After.

        Keyword arguments (query):
          keyword_id: Only matches of this keyword.
          platform: Only posts from this platform.
          status: Only mentions in this status. Omit for every status.
          relevant: true: only mentions the classifier scored relevant; false: only the rest (unclassified included).
          sentiment: Only this sentiment.
          intent: Only mentions carrying this intent (buy_intent, question, complaint, praise, comparison).
          person_id: Only this person (an id from /v1/people), merged accounts included. Implies includeMuted.
          include_muted: true: include mentions by people you muted, hidden by default.
          assignee_id: Only mentions assigned to this workspace member (user id).
          snoozed: true: only mentions currently snoozed. Otherwise snoozed mentions stay out until they wake.
          exclude_authors: Hide these authors: display names, handles or profile URLs. Repeatable, or one comma-separated value.
          min_relevance: Only mentions scored at least this; unclassified ones are excluded.
          min_followers: Only authors with at least this many followers. Unknown reach never passes.
          tags: Only authors your workspace tagged with any of these (exact, case-sensitive). Repeatable, or comma-separated.
          link_hosts: Only posts linking to any of these hosts, the host itself or a subdomain of it (octolens.com also matches blog.octolens.com). Repeatable, or comma-separated.
          q: Substring search in the post text.
          since: Only posts published at or after this instant (ISO 8601, or epoch ms).
          until: Only posts published at or before this instant (ISO 8601, or epoch ms)."""
        _coerce(params, {"platform": (_enum, _m.ExportMentionsCsvPlatform), "status": (_enum, _m.ExportMentionsCsvStatus), "sentiment": (_enum, _m.ExportMentionsCsvSentiment), "since": (_instant, None), "until": (_instant, None)})
        return _result(await _ops.mentions.export_mentions_csv.asyncio_detailed(client=self._client, **params))

    async def get(self, id: str) -> _m.Mention:
        """Get a mention

        One mention by id, as it appears in the list: the post, its author with reach and your tags, the classification, the priority score and the triage fields. Ids belong to your organization; any other id is a 404."""
        return _result(await _ops.mentions.get_mention.asyncio_detailed(id, client=self._client))

    async def search(self, **params: Any) -> _m.SearchMentionsResponse200:
        """List mentions

        Mentions matched to your keywords, filtered and paginated. Default order is newest match first; sort=priority ranks the last 30 days of matches by attention score. Page with nextCursor, passing the same filters and sort. A mention is one post matched to one keyword.

        Keyword arguments (query):
          keyword_id: Only matches of this keyword.
          platform: Only posts from this platform.
          status: Only mentions in this status. Omit for every status.
          relevant: true: only mentions the classifier scored relevant; false: only the rest (unclassified included).
          sentiment: Only this sentiment.
          intent: Only mentions carrying this intent (buy_intent, question, complaint, praise, comparison).
          person_id: Only this person (an id from /v1/people), merged accounts included. Implies includeMuted.
          include_muted: true: include mentions by people you muted, hidden by default.
          assignee_id: Only mentions assigned to this workspace member (user id).
          snoozed: true: only mentions currently snoozed. Otherwise snoozed mentions stay out until they wake.
          exclude_authors: Hide these authors: display names, handles or profile URLs. Repeatable, or one comma-separated value.
          min_relevance: Only mentions scored at least this; unclassified ones are excluded.
          min_followers: Only authors with at least this many followers. Unknown reach never passes.
          tags: Only authors your workspace tagged with any of these (exact, case-sensitive). Repeatable, or comma-separated.
          link_hosts: Only posts linking to any of these hosts, the host itself or a subdomain of it (octolens.com also matches blog.octolens.com). Repeatable, or comma-separated.
          q: Substring search in the post text.
          since: Only posts published at or after this instant (ISO 8601, or epoch ms).
          until: Only posts published at or before this instant (ISO 8601, or epoch ms).
          sort: newest: by match time, newest first. priority: by attention score, highest first; priority ranks the last 30 days of matches only, older ones stay reachable under newest. Cursors are specific to a sort.
          cursor: nextCursor from the previous page; pass the same filters and sort.
          limit: Page size, 1 to 100."""
        _coerce(params, {"platform": (_enum, _m.SearchMentionsPlatform), "status": (_enum, _m.SearchMentionsStatus), "sentiment": (_enum, _m.SearchMentionsSentiment), "since": (_instant, None), "until": (_instant, None), "sort": (_enum, _m.SearchMentionsSort)})
        return _result(await _ops.mentions.search_mentions.asyncio_detailed(client=self._client, **params))

    async def update(self, id: str, body: dict[str, Any] | _m.UpdateMentionBody | None = None, **fields: Any) -> _m.Mention:
        """Update a mention

        The one write on a mention. Set status to ignored or done to handle it (open puts it back), assign it to a workspace member, snooze it out of the feed, or leave an internal note. Null clears a field; omitted fields are untouched. Delivery and billing never change.

        Body: a dict, a model, or the fields as keyword arguments:
          status: ignored or done to handle it; open to put it back.
          assigneeId: A workspace member (user id), or null to unassign.
          snoozedUntil: ISO 8601 (or epoch ms) until which the mention leaves the feed; null wakes it.
          note: Internal note; null or empty clears it."""
        return _result(await _ops.mentions.update_mention.asyncio_detailed(id, client=self._client, body=_body(_m.UpdateMentionBody, body, fields)))

class _AsyncPeople:
    """people: export, get, list, merge, split, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    async def export(self, **params: Any) -> str:
        """Export people as CSV

        The same list as GET /v1/people (segmentId included) as CSV, one row per person with their contact columns: handle, followers, email, website, company, location, tags. Capped at 5,000 people. At most 6 exports per minute per workspace; a 429 carries Retry-After.

        Keyword arguments (query):
          platform: People with an account on this platform.
          q: Matches the display name or the profile handle or URL, case-insensitively.
          tag: Only people carrying this tag (exact, case-sensitive).
          muted: true: only muted people; false: only unmuted; omitted: everyone.
          since: Only people whose first matched mention is at or after this instant (ISO 8601, or epoch ms).
          segment_id: A saved segment applied on top of every other filter here. Unknown id: 404.
          platforms: People with an account on any of these platforms. Repeatable, or comma-separated.
          tags: People carrying any of these tags. Repeatable, or comma-separated.
          min_followers: At least this many followers. Unknown reach never matches.
          max_followers: At most this many followers.
          min_mentions: At least this many matched mentions.
          min_negative: At least this many negative mentions.
          intents: At least one mention carrying any of these intents.
          keyword_kinds: Mentioned a keyword of any of these kinds.
          never_keyword_kinds: Never mentioned a keyword of these kinds.
          new_since_days: First seen within this many days.
          link_hosts: People with at least one mention linking to any of these hosts, the host itself or a subdomain of it. Repeatable, or comma-separated.
          sort: mentions: most matches first. recent: last seen first. reach: most followers first, unknown last. new: first seen most recently first."""
        _coerce(params, {"platform": (_enum, _m.ExportPeopleCsvPlatform), "since": (_instant, None), "platforms": (_enum_list, _m.ExportPeopleCsvPlatformsItem), "keyword_kinds": (_enum_list, _m.ExportPeopleCsvKeywordKindsItem), "sort": (_enum, _m.ExportPeopleCsvSort)})
        return _result(await _ops.people.export_people_csv.asyncio_detailed(client=self._client, **params))

    async def get(self, id: str) -> _m.Person:
        """Get a person

        One person as your workspace sees them. An account merged into someone resolves to that person."""
        return _result(await _ops.people.get_person.asyncio_detailed(id, client=self._client))

    async def list(self, **params: Any) -> _m.ListPeopleResponse200:
        """List people

        The people behind your mentions: one row per person, with their accounts, reach, public profile, per-workspace stats and your annotations. Filter by platform, tag, follower range, mention counts, intents seen, keyword kinds mentioned or never mentioned, or a saved segment. Offset-paginated with a total.

        Keyword arguments (query):
          platform: People with an account on this platform.
          q: Matches the display name or the profile handle or URL, case-insensitively.
          tag: Only people carrying this tag (exact, case-sensitive).
          muted: true: only muted people; false: only unmuted; omitted: everyone.
          since: Only people whose first matched mention is at or after this instant (ISO 8601, or epoch ms).
          segment_id: A saved segment applied on top of every other filter here. Unknown id: 404.
          platforms: People with an account on any of these platforms. Repeatable, or comma-separated.
          tags: People carrying any of these tags. Repeatable, or comma-separated.
          min_followers: At least this many followers. Unknown reach never matches.
          max_followers: At most this many followers.
          min_mentions: At least this many matched mentions.
          min_negative: At least this many negative mentions.
          intents: At least one mention carrying any of these intents.
          keyword_kinds: Mentioned a keyword of any of these kinds.
          never_keyword_kinds: Never mentioned a keyword of these kinds.
          new_since_days: First seen within this many days.
          link_hosts: People with at least one mention linking to any of these hosts, the host itself or a subdomain of it. Repeatable, or comma-separated.
          sort: mentions: most matches first. recent: last seen first. reach: most followers first, unknown last. new: first seen most recently first.
          limit: Page size, 1 to 100.
          offset: Skip this many people. Offset paging: a grouped read over hundreds of people, not a stream."""
        _coerce(params, {"platform": (_enum, _m.ListPeoplePlatform), "since": (_instant, None), "platforms": (_enum_list, _m.ListPeoplePlatformsItem), "keyword_kinds": (_enum_list, _m.ListPeopleKeywordKindsItem), "never_keyword_kinds": (_enum_list, _m.ListPeopleNeverKeywordKindsItem), "sort": (_enum, _m.ListPeopleSort)})
        return _result(await _ops.people.list_people.asyncio_detailed(client=self._client, **params))

    async def merge(self, id: str, body: dict[str, Any] | _m.MergePeopleBody | None = None, **fields: Any) -> _m.Person:
        """Merge an account into a person

        Declare that this account and another person are the same human, for your workspace only. Their mentions, tags and notes combine under the person named by `into`.

        Body: a dict, a model, or the fields as keyword arguments:
          into (required): The person to fold this account into (their id)."""
        return _result(await _ops.people.merge_people.asyncio_detailed(id, client=self._client, body=_body(_m.MergePeopleBody, body, fields)))

    async def split(self, id: str) -> _m.Person:
        """Undo a merge

        The account becomes its own person again."""
        return _result(await _ops.people.split_person.asyncio_detailed(id, client=self._client))

    async def update(self, id: str, body: dict[str, Any] | _m.UpdatePersonBody | None = None, **fields: Any) -> _m.Person:
        """Update your annotations on a person

        Tags, notes and mute, for your workspace only. Mute hides their posts from your feed and every channel; ingest and billing never change.

        Body: a dict, a model, or the fields as keyword arguments:
          tags: Replaces the whole list.
          notes:
          muted:"""
        return _result(await _ops.people.update_person.asyncio_detailed(id, client=self._client, body=_body(_m.UpdatePersonBody, body, fields)))

class _AsyncSegments:
    """segments: create, delete, get, list, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    async def create(self, body: dict[str, Any] | _m.CreateSegmentBody | None = None, **fields: Any) -> _m.Segment:
        """Create a segment

        Body: a dict, a model, or the fields as keyword arguments:
          name (required):
          description:
          filter:"""
        return _result(await _ops.segments.create_segment.asyncio_detailed(client=self._client, body=_body(_m.CreateSegmentBody, body, fields)))

    async def delete(self, id: str) -> Any:
        """Delete a segment

        Nobody in it is affected."""
        return _result(await _ops.segments.delete_segment.asyncio_detailed(id, client=self._client))

    async def get(self, id: str) -> _m.Segment:
        """Get a segment"""
        return _result(await _ops.segments.get_segment.asyncio_detailed(id, client=self._client))

    async def list(self) -> _m.ListSegmentsResponse200:
        """List segments

        Your saved segments, each with the number of people in it right now (segments are evaluated on every read, never materialized), plus presets you can save as a starting point. Pass a segment id to GET /v1/people to list its members."""
        return _result(await _ops.segments.list_segments.asyncio_detailed(client=self._client))

    async def update(self, id: str, body: dict[str, Any] | _m.UpdateSegmentBody | None = None, **fields: Any) -> _m.Segment:
        """Update a segment

        Body: a dict, a model, or the fields as keyword arguments:
          name:
          description:
          filter: Replaces the whole filter."""
        return _result(await _ops.segments.update_segment.asyncio_detailed(id, client=self._client, body=_body(_m.UpdateSegmentBody, body, fields)))

class _AsyncAlerts:
    """alerts: create, delete, get, list, mute, run, test, unmute, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    async def create(self, body: dict[str, Any] | _m.CreateAlertBody | None = None, **fields: Any) -> _m.Alert:
        """Create an alert

        Body: a dict, a model, or the fields as keyword arguments:
          name (required):
          enabled:
          mode:
          filter:
          schedule: Required for daily alerts.
          event: Custom event name for webhook payloads; null for the mode default.
          channelIds: Channel ids from GET /v1/channels."""
        return _result(await _ops.alerts.create_alert.asyncio_detailed(client=self._client, body=_body(_m.CreateAlertBody, body, fields)))

    async def delete(self, id: str) -> Any:
        """Delete an alert"""
        return _result(await _ops.alerts.delete_alert.asyncio_detailed(id, client=self._client))

    async def get(self, id: str) -> _m.Alert:
        """Get an alert"""
        return _result(await _ops.alerts.get_alert.asyncio_detailed(id, client=self._client))

    async def list(self) -> _m.ListAlertsResponse200:
        """List alerts"""
        return _result(await _ops.alerts.list_alerts.asyncio_detailed(client=self._client))

    async def mute(self, id: str, body: dict[str, Any] | _m.MuteAlertAuthorsBody | None = None, **fields: Any) -> _m.Alert:
        """Mute authors on an alert

        Add authors to the alert's muted list without touching the rest of its filter. Links are read the way the dashboard reads them: a post link mutes its author, twitter.com becomes x.com, a Hacker News profile keeps its id. Authors already muted are skipped, so a retry is safe. An entry that names no person (a subreddit, a story) rejects the request with that entry named.

        Body: a dict, a model, or the fields as keyword arguments:
          authors (required): Profile or post links (x.com/name, linkedin.com/in/name, reddit.com/user/name, a post URL), handles (@name, u/name), Bluesky DIDs or display names. A link is stored as the author's profile; a plain name or handle matches that name on every platform."""
        return _result(await _ops.alerts.mute_alert_authors.asyncio_detailed(id, client=self._client, body=_body(_m.MuteAlertAuthorsBody, body, fields)))

    async def run(self, id: str) -> _m.RunAlertDigestResponse200:
        """Send a digest now"""
        return _result(await _ops.alerts.run_alert_digest.asyncio_detailed(id, client=self._client))

    async def test(self, id: str) -> _m.TestAlertResponse200:
        """Send a test through an alert's channels"""
        return _result(await _ops.alerts.test_alert.asyncio_detailed(id, client=self._client))

    async def unmute(self, id: str, body: dict[str, Any] | _m.UnmuteAlertAuthorsBody | None = None, **fields: Any) -> _m.Alert:
        """Unmute authors on an alert

        Remove authors from the alert's muted list without touching the rest of its filter. Name each one by the stored entry or by any link to that profile or its posts. Authors that are not muted are ignored, so a retry is safe.

        Body: a dict, a model, or the fields as keyword arguments:
          authors (required): Profile or post links (x.com/name, linkedin.com/in/name, reddit.com/user/name, a post URL), handles (@name, u/name), Bluesky DIDs or display names. A link is stored as the author's profile; a plain name or handle matches that name on every platform."""
        return _result(await _ops.alerts.unmute_alert_authors.asyncio_detailed(id, client=self._client, body=_body(_m.UnmuteAlertAuthorsBody, body, fields)))

    async def update(self, id: str, body: dict[str, Any] | _m.UpdateAlertBody | None = None, **fields: Any) -> _m.Alert:
        """Update an alert

        Body: a dict, a model, or the fields as keyword arguments:
          name:
          enabled:
          mode:
          filter: Replaces the whole filter.
          schedule:
          event:
          channelIds: Replaces the whole list."""
        return _result(await _ops.alerts.update_alert.asyncio_detailed(id, client=self._client, body=_body(_m.UpdateAlertBody, body, fields)))

class _AsyncChannels:
    """channels: create, delete, deliveries, get, list, rotate_secret, test, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    async def create(self, body: dict[str, Any] | _m.CreateSlackChannel | _m.CreateEmailChannel | _m.CreateWebhookChannel | None = None, **fields: Any) -> Any:
        """Create a channel

        Body: a dict with `kind` (slack, email, webhook) or a model; fields may also be passed as keyword arguments:
          kind:
          channelId: A Slack channel id from the connected workspace.
          channelName: The channel name, for the label.
          emails: Each address gets a confirmation link; workspace members are confirmed on sight.
          url: Where the signed POSTs go. https in production.
          label: A name for the channel; the host of the URL when omitted.
          headers: Extra request headers to send, for your own auth."""
        return _result(await _ops.alerts.create_channel.asyncio_detailed(client=self._client, body=_body({"slack": _m.CreateSlackChannel, "email": _m.CreateEmailChannel, "webhook": _m.CreateWebhookChannel}, body, fields)))

    async def delete(self, id: str) -> Any:
        """Delete a channel"""
        return _result(await _ops.alerts.delete_channel.asyncio_detailed(id, client=self._client))

    async def deliveries(self, id: str, **params: Any) -> _m.ListChannelDeliveriesResponse200:
        """List deliveries to a channel

        Keyword arguments (query):
          limit:"""
        return _result(await _ops.alerts.list_channel_deliveries.asyncio_detailed(id, client=self._client, **params))

    async def get(self, id: str) -> Any:
        """Get a channel"""
        return _result(await _ops.alerts.get_channel.asyncio_detailed(id, client=self._client))

    async def list(self) -> _m.ListChannelsResponse200:
        """List channels"""
        return _result(await _ops.alerts.list_channels.asyncio_detailed(client=self._client))

    async def rotate_secret(self, id: str) -> Any:
        """Rotate a webhook secret"""
        return _result(await _ops.alerts.rotate_webhook_secret.asyncio_detailed(id, client=self._client))

    async def test(self, id: str) -> _m.TestChannelResponse200:
        """Send a test to a channel"""
        return _result(await _ops.alerts.test_channel.asyncio_detailed(id, client=self._client))

    async def update(self, id: str, body: dict[str, Any] | _m.UpdateChannelBody | None = None, **fields: Any) -> Any:
        """Update a channel

        Body: a dict, a model, or the fields as keyword arguments:
          label:
          url: Webhooks only.
          headers: Webhooks only; replaces the whole set."""
        return _result(await _ops.alerts.update_channel.asyncio_detailed(id, client=self._client, body=_body(_m.UpdateChannelBody, body, fields)))

class _AsyncCompany:
    """company: get, update."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    async def get(self) -> _m.Company:
        """Get the company profile

        What the classifier knows about you: name, description, use cases, your own accounts, and the composed context it reads."""
        return _result(await _ops.company.get_company.asyncio_detailed(client=self._client))

    async def update(self, body: dict[str, Any] | _m.UpdateCompanyBody | None = None, **fields: Any) -> _m.Company:
        """Update the company profile

        Changing profile fields recomposes the classifier context; setting `context` directly overrides it until the next profile edit. Relevance scores for new mentions follow at once.

        Body: a dict, a model, or the fields as keyword arguments:
          name:
          description:
          useCases: Replaces the whole list.
          accounts:
          context: Overrides the composed context until the next profile edit."""
        return _result(await _ops.company.update_company.asyncio_detailed(client=self._client, body=_body(_m.UpdateCompanyBody, body, fields)))

class _AsyncAnalytics:
    """analytics: breakdown, series, share_of_voice, summary."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    async def breakdown(self, **params: Any) -> _m.AnalyticsBreakdown:
        """Mentions grouped by one dimension

        One table of matched, relevant and sentiment counts grouped by `by`: platform, keyword, sentiment, intent, status, hour (weekday and hour of day) or person. The window is `range` (7d, 30d, 90d, 365d, ending today) or `from` and `to`, cut into days in `timezone` (UTC by default); `keywordIds` and `platforms` narrow it; `compare=true` adds the period of the same length right before it. Time axis is the publish date.

        Keyword arguments (query):
          range_: Preset window ending today. Ignored when from or to is given. Default 30d.
          from_: First day, YYYY-MM-DD, inclusive, in `timezone`.
          to: Last day, YYYY-MM-DD, inclusive, in `timezone`. Default today.
          keyword_ids: Only these keyword ids. Repeatable, or comma-separated; omit for every keyword.
          platforms: Only these platforms. Repeatable, or comma-separated; omit for every platform.
          compare: true adds the period of the same length right before the window as `previous`.
          timezone: IANA zone the days are cut in (Europe/Madrid). Default UTC. One offset, the zone's at the end of the window, applies to the whole window.
          by: The dimension to group by: platform, keyword, sentiment (unclassified included), intent (a mention can carry several), status (open, ignored, done), hour (weekday and hour of day in `timezone`), person (who posted; anonymous posts are left out)."""
        _coerce(params, {"range_": (_enum, _m.GetAnalyticsBreakdownRange), "platforms": (_enum_list, _m.GetAnalyticsBreakdownPlatformsItem), "by": (_enum, _m.GetAnalyticsBreakdownBy)})
        return _result(await _ops.analytics.get_analytics_breakdown.asyncio_detailed(client=self._client, **params))

    async def series(self, **params: Any) -> _m.AnalyticsSeries:
        """Mentions over time

        Matched, relevant and sentiment counts per day or week across the window, as one total series or split per platform or per keyword with `by`. The window is `range` (7d, 30d, 90d, 365d, ending today) or `from` and `to`, cut into days in `timezone` (UTC by default); `keywordIds` and `platforms` narrow it; `compare=true` adds the period of the same length right before it. Time axis is the publish date.

        Keyword arguments (query):
          range_: Preset window ending today. Ignored when from or to is given. Default 30d.
          from_: First day, YYYY-MM-DD, inclusive, in `timezone`.
          to: Last day, YYYY-MM-DD, inclusive, in `timezone`. Default today.
          keyword_ids: Only these keyword ids. Repeatable, or comma-separated; omit for every keyword.
          platforms: Only these platforms. Repeatable, or comma-separated; omit for every platform.
          compare: true adds the period of the same length right before the window as `previous`.
          timezone: IANA zone the days are cut in (Europe/Madrid). Default UTC. One offset, the zone's at the end of the window, applies to the whole window.
          bucket: Point granularity. Default: day up to 90 days, week beyond. Weeks start on Monday.
          by: Split into one series per platform or per keyword (the top 20 by matched, the rest folded into "other"). Omit for one total series."""
        _coerce(params, {"range_": (_enum, _m.GetAnalyticsSeriesRange), "platforms": (_enum_list, _m.GetAnalyticsSeriesPlatformsItem), "bucket": (_enum, _m.GetAnalyticsSeriesBucket), "by": (_enum, _m.GetAnalyticsSeriesBy)})
        return _result(await _ops.analytics.get_analytics_series.asyncio_detailed(client=self._client, **params))

    async def share_of_voice(self, **params: Any) -> _m.ShareOfVoice:
        """Brand against competitors

        Every keyword matched in the window with its counts and its share of brand plus competitor matches; topic keywords are counted but stay out of the split. The window is `range` (7d, 30d, 90d, 365d, ending today) or `from` and `to`, cut into days in `timezone` (UTC by default); `keywordIds` and `platforms` narrow it; `compare=true` adds the period of the same length right before it. Time axis is the publish date.

        Keyword arguments (query):
          range_: Preset window ending today. Ignored when from or to is given. Default 30d.
          from_: First day, YYYY-MM-DD, inclusive, in `timezone`.
          to: Last day, YYYY-MM-DD, inclusive, in `timezone`. Default today.
          keyword_ids: Only these keyword ids. Repeatable, or comma-separated; omit for every keyword.
          platforms: Only these platforms. Repeatable, or comma-separated; omit for every platform.
          compare: true adds the period of the same length right before the window as `previous`.
          timezone: IANA zone the days are cut in (Europe/Madrid). Default UTC. One offset, the zone's at the end of the window, applies to the whole window."""
        _coerce(params, {"range_": (_enum, _m.GetShareOfVoiceRange), "platforms": (_enum_list, _m.GetShareOfVoicePlatformsItem)})
        return _result(await _ops.analytics.get_share_of_voice.asyncio_detailed(client=self._client, **params))

    async def summary(self, **params: Any) -> _m.AnalyticsSummary:
        """Headline counts for a window

        Matched and relevant mentions, distinct posts and people, sentiment, buying intent and questions, estimated reach, and where the matches stand in triage. The window is `range` (7d, 30d, 90d, 365d, ending today) or `from` and `to`, cut into days in `timezone` (UTC by default); `keywordIds` and `platforms` narrow it; `compare=true` adds the period of the same length right before it. Time axis is the publish date.

        Keyword arguments (query):
          range_: Preset window ending today. Ignored when from or to is given. Default 30d.
          from_: First day, YYYY-MM-DD, inclusive, in `timezone`.
          to: Last day, YYYY-MM-DD, inclusive, in `timezone`. Default today.
          keyword_ids: Only these keyword ids. Repeatable, or comma-separated; omit for every keyword.
          platforms: Only these platforms. Repeatable, or comma-separated; omit for every platform.
          compare: true adds the period of the same length right before the window as `previous`.
          timezone: IANA zone the days are cut in (Europe/Madrid). Default UTC. One offset, the zone's at the end of the window, applies to the whole window."""
        _coerce(params, {"range_": (_enum, _m.GetAnalyticsSummaryRange), "platforms": (_enum_list, _m.GetAnalyticsSummaryPlatformsItem)})
        return _result(await _ops.analytics.get_analytics_summary.asyncio_detailed(client=self._client, **params))

class _AsyncApiKeys:
    """api-keys: create, list, revoke."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    async def create(self, body: dict[str, Any] | _m.CreateApiKeyBody | None = None, **fields: Any) -> _m.CreateApiKeyResponse201:
        """Create an API key

        Mint a key for this workspace. The key itself is returned once; only its hash is stored.

        Body: a dict, a model, or the fields as keyword arguments:
          name: A label for the key; "default" when omitted.
          scope: read: GET only. write: everything."""
        return _result(await _ops.api_keys.create_api_key.asyncio_detailed(client=self._client, body=_body(_m.CreateApiKeyBody, body, fields)))

    async def list(self) -> _m.ListApiKeysResponse200:
        """List API keys"""
        return _result(await _ops.api_keys.list_api_keys.asyncio_detailed(client=self._client))

    async def revoke(self, id: str) -> Any:
        """Revoke an API key

        Takes effect at once on the API and within a few minutes on cached verifications."""
        return _result(await _ops.api_keys.revoke_api_key.asyncio_detailed(id, client=self._client))

class _AsyncSystem:
    """system: health."""

    def __init__(self, client: AuthenticatedClient) -> None:
        self._client = client

    async def health(self) -> _m.GetHealthResponse200:
        """getHealth"""
        return _result(await _ops.system.get_health.asyncio_detailed(client=self._client))

class Mentio:
    """The Mentio API: one object, one call per endpoint, grouped by resource.

    client = Mentio(api_key)
    mentions = client.mentions.search(platform="reddit", relevant=True)

    Every call returns the parsed response (the generated model, a str for CSV
    exports, None for a 204) or raises MentioError with the API's status, code
    and message. Enum-valued arguments take plain strings, instants take a
    datetime, an ISO 8601 string or epoch milliseconds, bodies take a dict, a
    model, or their fields as keyword arguments. `client` is the underlying
    AuthenticatedClient for anything the facade does not cover.
    """

    def __init__(
        self,
        api_key: str,
        *,
        base_url: str = DEFAULT_BASE_URL,
        timeout: float | None = 30.0,
        headers: dict[str, str] | None = None,
        httpx_args: dict[str, Any] | None = None,
    ) -> None:
        self.client = AuthenticatedClient(
            base_url=base_url.rstrip("/"),
            token=api_key,
            prefix="Bearer",
            headers=headers or {},
            timeout=httpx.Timeout(timeout) if timeout is not None else None,
            httpx_args=httpx_args or {},
        )
        self.keywords = _Keywords(self.client)
        self.mentions = _Mentions(self.client)
        self.people = _People(self.client)
        self.segments = _Segments(self.client)
        self.alerts = _Alerts(self.client)
        self.channels = _Channels(self.client)
        self.company = _Company(self.client)
        self.analytics = _Analytics(self.client)
        self.api_keys = _ApiKeys(self.client)
        self.system = _System(self.client)

    def __enter__(self) -> "Mentio":
        self.client.__enter__()
        return self

    def __exit__(self, *args: Any) -> None:
        self.client.__exit__(*args)

class AsyncMentio:
    """The Mentio API, awaitable: one object, one call per endpoint, grouped by resource.

    client = AsyncMentio(api_key)
    mentions = await client.mentions.search(platform="reddit", relevant=True)

    Every call returns the parsed response (the generated model, a str for CSV
    exports, None for a 204) or raises MentioError with the API's status, code
    and message. Enum-valued arguments take plain strings, instants take a
    datetime, an ISO 8601 string or epoch milliseconds, bodies take a dict, a
    model, or their fields as keyword arguments. `client` is the underlying
    AuthenticatedClient for anything the facade does not cover.
    """

    def __init__(
        self,
        api_key: str,
        *,
        base_url: str = DEFAULT_BASE_URL,
        timeout: float | None = 30.0,
        headers: dict[str, str] | None = None,
        httpx_args: dict[str, Any] | None = None,
    ) -> None:
        self.client = AuthenticatedClient(
            base_url=base_url.rstrip("/"),
            token=api_key,
            prefix="Bearer",
            headers=headers or {},
            timeout=httpx.Timeout(timeout) if timeout is not None else None,
            httpx_args=httpx_args or {},
        )
        self.keywords = _AsyncKeywords(self.client)
        self.mentions = _AsyncMentions(self.client)
        self.people = _AsyncPeople(self.client)
        self.segments = _AsyncSegments(self.client)
        self.alerts = _AsyncAlerts(self.client)
        self.channels = _AsyncChannels(self.client)
        self.company = _AsyncCompany(self.client)
        self.analytics = _AsyncAnalytics(self.client)
        self.api_keys = _AsyncApiKeys(self.client)
        self.system = _AsyncSystem(self.client)

    async def __aenter__(self) -> "AsyncMentio":
        await self.client.__aenter__()
        return self

    async def __aexit__(self, *args: Any) -> None:
        await self.client.__aexit__(*args)
